name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install aclocal
        run: |
          brew update
          brew install aclocal
    - name: autogen
      run:  ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
      
  test:
    
    runs-on: macos-latest
    
    steps:
    - name: test
      run: ./src/A61
