name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install autotools
      run: brew update && brew install autoconf automake libtool
    - name: Checkout flint
      run: git clone https://github.com/wbhart/flint2.git
    - name: Descend to flint
      run: cd flint2
    - name: Install flint
      run:  ./configure && make && make check && make install
    - name: Ascend from flint
      run: cd ..
    - name: Checkout antic 
      run: git clone https://github.com/wbhart/antic.git
    - name: Descend to antic
      run: cd antic 
    - name: Install antic
      run: ./configure && make && make install && make check
    - name: Ascend from antic
      run: cd ..
    - name: Checkout omf5
      run: git clone https://github.com/assaferan/omf5.git
    - name: Descend to omf5
      run: cd omf5
    - name: build
      run:  ./autogen.sh && ./configure && make
    - name: test
      run: ./src/A61
