name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install autotools
      run: brew update && brew install autoconf automake libtool
    - name: Checkout flint
      run: git clone https://github.com/wbhart/flint2.git
    - name: Descend to flint
      run: cd flint2
    - name: Install flint
      run: ./configure && make && make check && make install
    - name: Ascend from flint
      run: cd ..
    - name: Checkout antic 
      run: git clone https://github.com/wbhart/antic.git
    - name: Install antic
      run: cd antic && make && make install && make check
    - name: autogen
      run:  ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: test
      run: ./src/A61
