name: Build all dependencies and omf5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
          path: omf5
    - name: Checkout flint
      uses: actions/checkout@v3
      with:
        repository: wbhart/flint2
        path: flint2
    - name: Checkout antic
      uses: actions/checkout@v3
      with:
        repository: wbhart/antic
        path: antic
        ref: v0.2.1
    - name: Checkout carat
      uses: actions/checkout@v3
      with:
        repository: lbfm-rwth/carat
        path: carat
    - name: Install autotools
      run: brew update && brew install autoconf automake libtool
    - name: Install flint
      run:  cd flint2 && ./bootstrap.sh && ./configure && make && make install && cd ..
    - name: Install antic
      run: cd antic && ./configure && make && make install && cd ..
    - name: Install carat
      run: cd carat && ./autogen.sh && ./configure && make && make install && cp libfunctions.a /usr/local/lib && cd ..
    - name: build
      run:  cd omf5 && ./autogen.sh && ./configure && make
    - name: ld_path
      run: export LD_LIBRARY_PATH="/usr/local/lib:../flint2:../antic:../carat"
    - name: test
      run: ./omf5/src/omf5 -tests
