name: Build all dependencies and omf5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          path: omf5

    - name: Install autotools
      run: brew update && brew install autoconf automake libtool

    - name: Checkout flint
      uses: actions/checkout@v3
      with:
        repository: flintlib/flint2
        path: flint2

    - name: Install flint
      run:  cd flint2 && ./bootstrap.sh && ./configure && make && make install && cd ..

    - name: Checkout antic
      uses: actions/checkout@v3
      with:
        repository: flintlib/antic
        path: antic

    - name: Install antic
      run: cd antic && ./configure && gcc --version && make && make install && cd ..

    - name: Checkout carat
      uses: actions/checkout@v3
      with:
        repository: lbfm-rwth/carat
        path: carat

    - name: Install carat
      run: cd carat && ./autogen.sh && ./configure && make && make install && cp libfunctions.a /usr/local/lib && cd ..

    - name: build
      run:  cd omf5 && ./autogen.sh && ./configure && make

    - name: test
      run: ./omf5/src/omf5 -tests
