name: Build all dependencies and omf5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
          # switch to latest
        os: [ ubuntu-latest, macos-10.15 ]
        include:
          - cc_cmd: clang
            os: macos-10.15
          - cc_cmd: gcc
            os: ubuntu-latest
          - pkg_man: brew
            os: macos-10.15
          - pkg_man: sudo apt-get
            os: ubuntu-latest
          - add_pkgs: libgmp-dev libmpfr-dev libtool-bin
            os: ubuntu-latest
          - add_pkgs: mpfr gmp
            os: macos-10.15
          - make_install: make install
            os: macos-10.15
          - make_install: sudo make install
            os: ubuntu-latest
          - cp_cmd: cp
            os: macos-10.15
          - cp_cmd: sudo cp
            os: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          path: omf5

    - name: Install dependencies
      run: |
          ${{ matrix.pkg_man }} update
          ${{ matrix.pkg_man }} install autoconf automake libtool ${{ matrix.add_pkgs }}

    - name: Checkout flint
      uses: actions/checkout@v3
      with:
        repository: flintlib/flint2
        path: flint2

    - name: Install flint
      run: |
        cd flint2
        ./bootstrap.sh
        cat configure
        ./configure
        make
        make install
        cd ..

    - name: Checkout antic
      uses: actions/checkout@v3
      with:
        repository: flintlib/antic
        path: antic

    - name: Install antic
      run: |
        cd antic
        ./configure
        make
        make install
        cd ..

    - name: Checkout carat
      uses: actions/checkout@v3
      with:
        repository: lbfm-rwth/carat
        path: carat

    - name: Install carat
      run: |
        cd carat
        ./autogen.sh
        ./configure
        make
        make install
        cp libfunctions.a /usr/local/lib
        cd ..

    - name: build
      run: |
        cd omf5
        ./autogen.sh
        ./configure
        make

    - name: test
      run: ./omf5/src/omf5 -tests
