name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
          path: omf5
    - name: Checkout flint
      uses: actions/checkout@v3
      with:
        repository: wbhart/flint2
        path: flint2
    - name: Checkout antic
      uses: actions/checkout@v3
      with:
        repository: wbhart/antic
        path: antic
    - name: Install autotools
      run: brew update && brew install autoconf automake libtool
    - name: Descend to flint
      run: cd flint2
    - name: Install flint
      run:  ./configure && make && make check && make install
    - name: Ascend from flint
      run: cd ..
    - name: Descend to antic
      run: cd antic 
    - name: Install antic
      run: ./configure && make && make install && make check
    - name: Ascend from antic
      run: cd ..
    - name: Descend to omf5
      run: cd omf5
    - name: build
      run:  ./autogen.sh && ./configure && make
    - name: test
      run: ./src/A61
