name: Skip compilation of flint

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
  
    runs-on: ${{ matrix.on }}
    
    strategy: 
      
      matrix:
        on: [ ubuntu-20.04, macos-10.15 ]
        libflint: [ 2.8.4 ]
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
          path: omf5
    - name: Checkout antic
      uses: actions/checkout@v3
      with:
        repository: wbhart/antic
        path: antic
    - name: Checkout carat
      uses: actions/checkout@v3
      with:
        repository: lbfm-rwth/carat
        path: carat    
    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with: { mamba-version: "*", channels: "conda-forge", channel-priority: true, python-version: "3.9" }
    - name: Install flint
      shell: bash -l {0}
      run: |
          mamba install -y libflint=${{ matrix.libflint }} c-compiler gmp mpfr
          conda list
    - name: Install antic
      shell: bash -l {0}
      run: |
          cd antic
          ./configure --prefix=$CONDA_PREFIX --with-flint=$CONDA_PREFIX --with-gmp=$CONDA_PREFIX --with-mpfr=$CONDA_PREFIX
          make
          make install
          make check
          cd ..
    - name: Install carat
      run: cd carat && ./autogen.sh && ./configure && make && make install && cp libfunctions.a /usr/local/lib && cd ..
    - name: build
      run:  cd omf5 && ./autogen.sh && ./configure && make
    - name: test
      run: ./omf5/src/omf5 -tests
