name: Skip compilation of flint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.on }}

    strategy:

      matrix:
        on: [ ubuntu-latest, macos-latest ]
        libflint: [ 2.8.4 ]
        antic : [ 0.2.5 ]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
          path: omf5



    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with: { mamba-version: "*", channels: "conda-forge", channel-priority: true, python-version: "3.9" }
    - name: Install flint and antic
      shell: bash -l {0}
      run: |
          mamba install -y libflint=${{ matrix.libflint }} antic=${{ matrix.antic }} c-compiler gmp mpfr
          conda list



    - name: Checkout carat
      uses: actions/checkout@v3
      with:
        repository: lbfm-rwth/carat
        path: carat

    - name: Install carat
      run: |
          cd carat
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo cp libfunctions.a /usr/local/lib
          cd ..

    - name: build
      shell: bash -l {0}
      run: |
        cd omf5
        ./autogen.sh
        FLINT_PATH=$CONDA_PREFIX GMP_PATH=$CONDA_PREFIX ANTIC_PATH=$CONDA_PREFIX CARAT_PATH=/urs/local ./configure
        make

    - name: test
      run: ./omf5/src/omf5 -tests
